# gcr-client


# compose syntax version.
version: "3.6"

# services declaration.
services:
  # MySQL
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gcr-client
      - MYSQL_USER=gcr-client
      - MYSQL_PASSWORD=gcr-client
      - MYSQL_DATABASE=gcr-client
    ports:
      - target: 3306
        published: 3306
  # Web Application
  web:
    image: ambientum/php:7.3-nginx
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=true
      - OPCACHE_MODE=normal
      - PHP_MEMORY_LIMIT=256M
    ports:
      - target: 8080
        published: 8080
      - target: 8083
        published: 8083
    links:
      - mysql

# volumes declaration.
volumes:
  # mysql-data
  mysql-data:
    driver: local
  # dot-config
  dot-config:
    driver: local
  # dot-cache
  dot-cache:
    driver: local
  # dot-local
  dot-local:
    driver: local
  # dot-composer
  dot-composer:
    driver: local
